
Vagrant.configure("2") do |config|

    config.vm.define "one" do |one|
        one.vm.box = "chrism/win2012-r2-x64"
        one.vm.hostname = "winweb"
        #one.vm.network :private_network, ip: "192.168.33.12"
            one.vm.provider "virtualbox" do |va|

            end
    end
end