





Vagrant.configure("2") do |config|

    config.vm.define "one" do |one|
        one.vm.box = "opentable/win-2012r2-datacenter-amd64-nocm"
        one.vm.hostname = "vmone"
        #one.vm.network :private_network, ip: "192.168.33.11"
            one.vm.provider "virtualbox" do |va|

            end
    end
end