API_VERSION = "2"
GUEST_IP = "192.168.33.11"
HOST_IP = "192.168.33.1"
HOSTNAME = "windb1"
BOX = "MC/win2012-r2-x64-A"
RAM = "1024"
CPU = "2"


Vagrant.configure(API_VERSION) do |config|

  config.vm.guest = :windows
  config.vm.communicator = :winrm

  config.vm.box = BOX

  config.vm.network :forwarded_port, guest: 3389, host: 33389
  config.vm.network :forwarded_port, guest: 5986, host: 55986
  config.vm.network :forwarded_port, guest: 5985, host: 55985, id: "winrm",
  auto_correct: true

  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600

  config.vm.provider :virtualbox do |vb|
    vb.cpus = CPU
    vb.memory = RAM
    vb.name = HOSTNAME

  config.vm.hostname = HOSTNAME

 
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "provisioning/playbook.yml"

  end


end

