Vagrant.configure(2) do |config|
    config.vm.guest = :windows
    config.vm.communicator = "winrm"
    config.vm.boot_timeout = 600
    config.vm.graceful_halt_timeout = 600
    config.vm.network :forwarded_port, guest: 3389, host: 3389
    config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

    config.vm.define "one" do |one|
        one.vm.box = "chrism/win2012-r2-x64"
        one.vm.hostname = "windbOne"
        one.vm.network :private_network, ip: "192.168.33.11"
        one.vm.provider "virtualbox" do |va|

        end
    end
end