





Vagrant.configure("2") do |config|

    config.vm.define "one" do |one|
        one.vm.box = "sitestacker/win12-sql14"
        one.vm.hostname = "windb"
        #one.vm.network :private_network, ip: "192.168.33.11"
            one.vm.provider "virtualbox" do |va|

            end
    end
end