# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION ) do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false

  config.vm.hostname = "centos7"
  config.vm.network :private_network, ip: "192.168.33.22"


  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.storage_pool_name = "default"
  end

  # Ansible provisioner.
  #config.vm.provision "ansible" do |ansible|
  #  ansible.verbose = "v"
  #  ansible.playbook = "provisioning/playbook.yml"
  #  ansible.sudo = true
  #end

end