---
- hosts: centos
  gather_facts: yes
  become: yes


  tasks:
  - name: disable selinux
    command: /sbin/setenforce 0

  - name: disable firewalld
    systemd:
    state: stopped
    enabled: no
    name: firewalld



  vars_files:
    - vars/main.yml



  roles:




