# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "one" do |one|
        one.vm.box = "opentable/win-2012r2-datacenter-amd64-nocm"
        one.vm.hostname = "vmone"
        one.vm.network :private_network, ip: "192.168.33.11"
            one.vm.provider "virtualbox" do |va|
                va.name = "VM1"
                va.memory = 1024
                va.cpus = 2
            end
    end

    config.vm.define "two" do |two|
        two.vm.box = "opentable/win-2012r2-datacenter-amd64-nocm"
        two.vm.hostname = "vmtwo"
        two.vm.network :private_network, ip: "192.168.33.22"
            two.vm.provider "virtualbox" do |vb|
                vb.name = "VM2"
                vb.memory = 1024
                vb.cpus = 2
            end
    end


end
