# -*- mode: ruby -*-
# vi: set ft=ruby :

#VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.define :dbserver do |dbserver|
     dbserver.vm.box = "centos/7"
     dbserver.vm.provider :libvirt do |domain|
        domain.memory = 2048
        domain.cpus = 2
        domain.nested = true
        domain.volume_cache = 'none'
     end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"

  end

end
