# -*- mode: ruby -*-
# vi: set ft=ruby :

#VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.define :spacewalk do |spacewalk|
     spacewalk.vm.box = "centos/7"
     spacewalk.vm.provider :libvirt do |domain|
        domain.memory = 4096
        domain.cpus = 2
        domain.nested = true
        domain.host = "spacewalk-server"
        domain.volume_cache = 'none'
     end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"

  end

end
