---
- name: Install and start Apache {{ webservice }}
  hosts: web
  vars_files:
      - vars/vars.yml

  tasks:
    - name: package is present {{ webservice }} 
      yum:
      name: "{{ webservice }}"
        state: present
        
    - name: correct index.html is present
      copy:
        src: files/index.html
        dest: "{{ destination }}"

    - name: {{ webservice }} is started
      service:
        name: "{{ webservice }}"
        state: started
        enabled: true

