---
- hosts: app_servers
  become: yes


  tasks:




    - name: disable network manager
      systemd:
        name: NetworkManager
        state: stopped
        enabled: no

    - name: disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no




  vars_files:
    - vars.yml


