# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION ) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.insert_key = false

  config.vm.hostname = "ubuntu"
  config.vm.network :private_network, ip: "192.168.33.200"


  config.vm.provider :virtualbox do |v|
    v.name = "ubuntu"
    v.memory = 1024
    v.cpus = 2
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.sudo = true
  end

end