# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "one" do |one|
        one.vm.box = "ubuntu/trusty64"
        one.vm.hostname = "prima"
    end

    config.vm.define "two" do |two|
        two.vm.box = "ubuntu/trusty64"
        two.vm.hostname = "seconda"

    end
end