# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION ) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.insert_key = false

  config.vm.hostname = "ubuntu1"
  config.vm.network :private_network, ip: "192.168.2.101"


  config.vm.provider :virtualbox do |v|
    v.name = "ubuntu1"
    v.memory = 1024
    v.cpus = 2
  end

end

Vagrant.configure(VAGRANTFILE_API_VERSION ) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.insert_key = false

  config.vm.hostname = "ubuntu2"
  config.vm.network :private_network, ip: "192.168.2.102"


  config.vm.provider :virtualbox do |v|
    v.name = "ubuntu2"
    v.memory = 1024
    v.cpus = 2
  end

end